"""changes in user cascade

Revision ID: 4320f04cf4f6
Revises: 39b9971336a2
Create Date: 2026-06-24 16:31:33.271208

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4320f04cf4f6'
down_revision: Union[str, Sequence[str], None] = '39b9971336a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('commitments_user_id_fkey'), 'commitments', type_='foreignkey')
    op.create_foreign_key(None, 'commitments', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'commitments', type_='foreignkey')
    op.create_foreign_key(op.f('commitments_user_id_fkey'), 'commitments', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
