"""add is_successful to metric_log

Revision ID: 43fe7e041818
Revises: 4320f04cf4f6
Create Date: 2026-08-10 10:35:32.704480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43fe7e041818'
down_revision: Union[str, Sequence[str], None] = '4320f04cf4f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('metric_logs', sa.Column('is_successful', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('metric_logs', 'is_successful')
    # ### end Alembic commands ###
