"""add index to metric_id and isuccessful in MetricLogs

Revision ID: 774265420547
Revises: 43fe7e041818
Create Date: 2026-09-16 01:45:03.594818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '774265420547'
down_revision: Union[str, Sequence[str], None] = '43fe7e041818'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_metric_logs_daily_entry_id'), 'metric_logs', ['daily_entry_id'], unique=False)
    op.create_index(op.f('ix_metric_logs_is_successful'), 'metric_logs', ['is_successful'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_metric_logs_is_successful'), table_name='metric_logs')
    op.drop_index(op.f('ix_metric_logs_daily_entry_id'), table_name='metric_logs')
    # ### end Alembic commands ###
