"""add core behavioral models

Revision ID: c88110f0baff
Revises: b7452090e919
Create Date: 2026-06-18 23:47:37.954359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c88110f0baff'
down_revision: Union[str, Sequence[str], None] = 'b7452090e919'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('sleep_hours', sa.Float(), nullable=False),
    sa.Column('deep_work_hours', sa.Float(), nullable=True),
    sa.Column('distraction_hours', sa.Float(), nullable=True),
    sa.Column('mood_score', sa.Integer(), nullable=True),
    sa.Column('energy_score', sa.Integer(), nullable=True),
    sa.Column('journal_entry', sa.String(), nullable=True),
    sa.Column('what_avoided', sa.String(), nullable=True),
    sa.Column('biggest_win', sa.String(), nullable=True),
    sa.Column('biggest_failure', sa.String(), nullable=True),
    sa.Column('what_can_be_different', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date', name='uq_user_daily_entry')
    )
    op.create_table('tracking_metrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('commitment_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('metric_type', sa.String(), nullable=False),
    sa.Column('operator', sa.String(), nullable=False),
    sa.Column('target_value', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['commitment_id'], ['commitments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('metric_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('daily_entry_id', sa.UUID(), nullable=False),
    sa.Column('metric_id', sa.UUID(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['daily_entry_id'], ['daily_entries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['metric_id'], ['tracking_metrics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('day_reset_hour', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'day_reset_hour')
    op.drop_table('metric_logs')
    op.drop_table('tracking_metrics')
    op.drop_table('daily_entries')
    # ### end Alembic commands ###
