"""add index to metric_id and isuccessful in MetricLogs

Revision ID: d7f6d8375c9f
Revises: 774265420547
Create Date: 2026-09-16 01:48:36.706324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7f6d8375c9f'
down_revision: Union[str, Sequence[str], None] = '774265420547'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
